"DOTAAbilities"
{
    "ability_maker"
    {
        // General
        //-------------------------------------------------------------------------------------------------------------
        "BaseClass"                     "ability_lua"
        "ScriptFile"                    "abilities/ability_maker.lua"
        "AbilityTextureName"            "meepo_earthbind"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_NO_TARGET"
    }
}